name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to get the version from git describe

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24.x
        cache: true

    - name: Install dependencies
      run: make fetch

    - name: Run tests
      run: make test

    - name: Build
      run: make build-release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jabba
        path: |
          release/**
        if-no-files-found: ignore
