name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Run tests (make test)
        run: make test
        shell: bash

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to get the version from git describe

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
        cache: true

    - name: Install dependencies
      run: make fetch

    - name: Run tests
      run: make test

    - name: Build
      run: make build-release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jabba
        path: |
          release/**
        if-no-files-found: ignore
