name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.24.x]

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to get the version from git describe

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: make fetch

    - name: Run tests
      run: make test

    - name: Build
      run: make build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jabba-${{ runner.os }}
        path: |
          jabba
          jabba.exe
        if-no-files-found: ignore
